### ISSUE TITLE
Error in .local(.Object, ...) : 

### ISSUE THREAD

**Issue by Thorsten-Behrens** [stevenpawley/Rsagacmd#13]
Dear Steven,

I have a problem under Linux. On Windows 10 I have no issues. 
Rsagacmd is running, but crashes at some stage and does not return the raster data, which however is correctly generated. I can load it manually into any GIS. The only message, without any further information, I get is:
> Error in .local(.Object, ...) : 

The session info is:
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10
other attached packages:
  [1] Rsagacmd_0.1.0 raster_3.4-5   sp_1.4-5      

and the code:

>library(Rsagacmd)
setwd("/media/workspace/SSD2/RTests/")
eSagaCmd = saga_gis()
rPo = eSagaCmd$ta_lighting$topographic_openness(dem = raster("DEM.tif"), pos =  "pos.tif", .all_outputs = F)

I just tested some further commands of your package and for example 
>saga_env(saga_bin = NULL, opt_lib = NULL, backend = "raster")

fails with:
>Error in saga_env(saga_bin = NULL, opt_lib = NULL, backend = "raster") : 
  could not find function "saga_env" (translated from German...)

Do you have any suggestion or idea what might cause this? 

Thanks a lot in advance,
Thorsten

**Comment by stevenpawley** [comment]
Hi Thorsten,

Sorry for the delayed response, is this still causing an issue? I haven't had such a problem and can't reproduce this off-hand. I'm going to submit an update (with support for stars) and a few bug fixes to CRAN today. However, I don't think that this relates to your problem; Rsagacmd should be able to find the `saga_env` function because it is an internal function to the package namespace. If you have a fully reproducible example I'm happy to run some tests.

**Comment by Thorsten-Behrens** [comment]
Hi Steven,

thanks for your reply!

The problem seems to be related to the raster data driver - and is probably my fault. I did not specify the _raster_format_. This seem to be fine under Windows but nor under Linux. The files are written but cannot be read.

Best wishes,
Thorsten
