### ISSUE TITLE
Error: Unknown option 'RADIUS' when calculating TPI

### ISSUE THREAD

**Issue by tuulri** [stevenpawley/Rsagacmd#16]
Hi,

I´ve been trying to calculate topographic position index using Rsagacmd:
tpi100 <- saga$ta_morphometry$topographic_position_index_tpi(DEM, radius=100)

But always getting an error:
Error: Unknown option 'RADIUS'

If I run the tool without 'radius' argument, it works (though, then there´s no idea what was the used radius). In SAGA GUI TPI calculation also works fine. 

Could there be some bug in Rsagacmd or what could be the reason for the error? I´m using SAGA 8.0 and R 4.0.4.

Best regards,
Tuuli Rissanen

**Comment by stevenpawley** [comment]
Thanks for reporting. This is a bug with Rsagacmd, something that was deliberately introduced recently because SAGA-GIS < 8 had a difference in the parameters between the GUI and the command line for this tool, which I was deliberately catching. See: https://sourceforge.net/p/saga-gis/bugs/285/

It looks like the SAGA developers have changed this behaviour for version 8; I'll try release a new version over the next few days.

**Comment by tuulri** [comment]
Hi Steve,
That makes sense, thanks for the explanation. 

Looking forward to a new version, many thanks for your great R-package!

**Comment by stevenpawley** [comment]
TPI should be fixed with 1353674. Closing for now.
