### ISSUE TITLE
ta_hydrology upslope area requires GUI to execute

### ISSUE THREAD

**Issue by chljl** [stevenpawley/Rsagacmd#27]
I got a problem using the function saga$ta_hydrology$upslope_area() in Rstudio (Windows 11). The function gives the following error message:
 ! Error: tool needs graphical user interface [Upslope Area]
and does not run.

I've tried different versions of SAGA, 8.4, 9.1, and also 7.8 in OSGeo4w. All have the same result.  

I found others have the same issue when using this tool in QGIS. See the post: https://github.com/qgis/QGIS/issues/44514#issuecomment-894832603 

It looks like the problem is that Rsagacmd does not call the right function but calls the interactive one.

**Comment by stevenpawley** [comment]
Thanks for reporting this - I'll look into it and I've run into couple of issues like this with the command line tool

**Comment by stevenpawley** [comment]
Thanks for this, should be solved with https://github.com/stevenpawley/Rsagacmd/commit/26f6a2eedab28f398831baafac62c27004e09652 - please install from GitHub, test and reopen if there is a problem still. The post to https://github.com/qgis/QGIS/issues/44514#issuecomment-894832603 was also very helpful - thanks. This is a strange artifact of the SAGA command line because even though it only displays the non-interactive tool options, running the tool by its name causes the interactive version to run, so you have to explicitly supply the tool ID. Might be something to also suggest to the SAGA developers because this could confuse users even when just running things in the terminal.

**Comment by rhurlin** [comment]
> [...] Might be something to also suggest to the SAGA developers because this could confuse users even when just running things in the terminal.

Hi Steven,
I just reported this bug at SourceForge, the home of SAGA GIS, as Bug 307 [saga_cmd ta_hydrology 'Upslope Area' errors](https://sourceforge.net/p/saga-gis/bugs/307/).

**Comment by stevenpawley** [comment]
Thanks for that!

**Comment by rhurlin** [comment]
The following to commits did solve the underlying problem in **SAGA GIS**, so with its next release (> v9.2.0) the tool `Upslope Area` should work as expected ...

https://sourceforge.net/p/saga-gis/code/ci/ace62642a05b209ae6f8d90d41fb87fb65adaa15/
https://sourceforge.net/p/saga-gis/code/ci/6c0fb4e42e8d19379f04a4bbe18a354208c98d55/
