### ISSUE TITLE
Running in parallel and core usage

### ISSUE THREAD

**Issue by Pang-SEH** [stevenpawley/Rsagacmd#29]
Hi,

Thanks again for developing this package. Wanted to clarify on how cores are used through Rsagacmd. I understand that SAGA automatically detects cores and maximises them for functions, does that carry over into Rsagacmd? I can see that there is a way to limit core usage [in saga_configure(core = NULL)], which I assume limits what SAGA can use. Are functions from SAGA automatically run in parallel in R, i.e., should I avoid putting Rsagacmd functions inside a foreach or other parallel loops?

For context, I am processing 50 years of monthly temperature and precipitation data into relevant bioclimatic variables, developing annual bioclimatic variables. Should I just run my saga function individually for each year, or can I run the processing for each year in parallel?

Cheers,
Sean

**Comment by stevenpawley** [comment]
Hi Sean,

Unless you specify the cores in Rsagacmd, it should be using the default,
or at least what is specified in the saga configuration .ini file that SAGA
also generates. This is usually to use all available cores.

In terms of whether you should parallelize, I don't know whether the
bioclimate tools are already parallelized - many SAGA-GIS tools are because
even the map calculations using openMP under the hood. What represents the
most efficient approach can also depend on the grid size, the
dimensionality of the 'job' etc., i.e., sometimes even if an operation is
multithreaded, it can be faster to run a task without multithreading and
scale-out by running in job in parallel, but this is case specific

**Comment by Pang-SEH** [comment]
Thanks Steven, that was very helpful. I will run some tests to see what might be the fastest approach!
